#!/usr/bin/env bash
set -e

# =====================
# Usage
# =====================
usage() {
  echo "Usage: $0 [options]"
  echo
  echo "Options:"
  echo "  --config PATH              Path to config YAML"
  echo "  --training-data-path PATH  Path to training data"
  echo "  --run-name NAME            Run name (default: autogenerated)"
  echo "  --python-script PATH       Path to training script"
  echo "  -h, --help                 Show this help message"
  exit 1
}

# =====================
# Resolve paths
# =====================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "SCRIPT_DIR: $SCRIPT_DIR"
echo "PROJECT_ROOT: $PROJECT_ROOT"

# =====================
# Defaults
# =====================
PYTHON_SCRIPT="$PROJECT_ROOT/src/scripts/train.py"
CONFIG_PATH="$PROJECT_ROOT/src/config/logistic_regression.yaml"
TRAINING_DATA_PATH="/home/mlops/Repository/aio2025-mlops-project01/data-pipeline/churn_feature_store/churn_features/feature_repo/data/processed_churn_data.parquet"

TIMESTAMP="$(date +"%Y%m%d_%H%M%S")"
RUN_NAME="baseline-logistic_regression_${TIMESTAMP}"

# =====================
# Parse arguments
# =====================
while [[ $# -gt 0 ]]; do
  case "$1" in
    --config)
      CONFIG_PATH="$2"
      shift 2
      ;;
    --training-data-path)
      TRAINING_DATA_PATH="$2"
      shift 2
      ;;
    --run-name)
      RUN_NAME="$2"
      shift 2
      ;;
    --python-script)
      PYTHON_SCRIPT="$2"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Unknown argument: $1"
      usage
      ;;
  esac
done

# =====================
# Python path
# =====================
export PYTHONPATH="$PROJECT_ROOT"

# =====================
# Echo resolved config
# =====================
echo "PYTHON_SCRIPT: $PYTHON_SCRIPT"
echo "CONFIG_PATH: $CONFIG_PATH"
echo "TRAINING_DATA_PATH: $TRAINING_DATA_PATH"
echo "RUN_NAME: $RUN_NAME"

# =====================
# Train
# =====================
python "$PYTHON_SCRIPT" \
  --config "$CONFIG_PATH" \
  --training-data-path "$TRAINING_DATA_PATH" \
  --run-name "$RUN_NAME"
